version: "3.8"

services:
  # Servicio de PHP y Apache (backend)
  php-apache:
    build: .
    container_name: php-apache
    ports:
      - "3000:80"  # Backend en el puerto 3000
    volumes:
      - ./backend:/var/www/html/backend  # Monta la carpeta backend
      - ./frontend:/var/www/html/frontend  # Monta el frontend
      - ./vendor:/var/www/html/backend/vendor 
      - ./php-sessions:/var/lib/php/sessions
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf  # Monta la configuración de Apache
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql

  # Servicio de MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: mygameslist
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  # Servicio de phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"  # phpMyAdmin en el puerto 8081
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

  # Servicio de frontend (Nginx)
  frontend:
    image: nginx:latest
    container_name: nginx-frontend
    ports:
      - "5500:80"  # Frontend en el puerto 5500
    volumes:
      - ./frontend:/usr/share/nginx/html  # Monta la carpeta frontend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./node_modules:/usr/share/nginx/html/node_modules  # Monta node_modules
    depends_on:
      - php-apache